stages:
  - docker

docker:
  stage: docker

  image: docker:latest

  services:
    - docker:dind

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" 

  # build-master:
  #   stage: build
  #   script:
  #     - docker build --pull -t "$CI_REGISTRY_IMAGE" .
  #     - docker push "$CI_REGISTRY_IMAGE"
  #   only:
  #     - master

  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - master