stages:
  - docker
  - deploy

docker:
  stage: docker

  image: docker:latest

  services:
    - docker:dind

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" 

  # build-master:
  #   stage: build
  #   script:
  #     - docker build --pull -t "$CI_REGISTRY_IMAGE" .
  #     - docker push "$CI_REGISTRY_IMAGE"
  #   only:
  #     - master

  script:
    - echo "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - master
deploy:
  stage: deploy

  image: ayufan/openshift-cli

  script: 
    - oc login "$OPENSHIFT_SERVER" --token="$OPENSHIFT_TOKEN" --insecure-skip-tls-verify 
    - oc import-image express-load-balancer